from __future__ import annotations

import csv
import html
import io
import json
from datetime import datetime
from typing import Any

from .analysis import DuplicateCandidate, PulseReport, age_days, idle_days
from .models import WorkItem


def render_markdown(report: PulseReport, *, limit: int = 10) -> str:
    metrics = report.metrics
    lines = [
        f"# Maintainer Pulse: {report.repository}",
        "",
        f"Generated: {report.generated_at.isoformat(timespec='seconds')}",
        "",
        "## Health Snapshot",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
        f"| Health score | {metrics.health_score}/100 |",
        f"| Open issues | {metrics.open_issues} |",
        f"| Open pull requests | {metrics.open_pull_requests} |",
        f"| Release blockers | {metrics.release_blockers} |",
        f"| Stuck pull requests | {metrics.stuck_pull_requests} |",
        f"| Response debt | {metrics.response_debt} |",
        f"| Stale items ({report.stale_days}+ idle days) | {metrics.stale_items} |",
        f"| Closed in last 90 days | {metrics.recent_closed} |",
        f"| Median days to close | {_display_optional(metrics.median_days_to_close)} |",
        "",
        "## Recommended Maintainer Block",
        "",
    ]
    lines.extend(f"- {recommendation}" for recommendation in report.recommendations)
    lines.append("")

    if report.ai_summary:
        lines.extend(
            [
                "## AI Maintainer Summary",
                "",
                f"Provider: {report.ai_provider or 'unknown'}",
                f"Model: {report.ai_model or 'unknown'}",
                "",
                "AI-generated guidance is advisory. Verify repository context before acting.",
                "",
                report.ai_summary.strip(),
                "",
            ]
        )

    for title, key in (
        ("Release Blockers", "release_blockers"),
        ("Stuck Pull Requests", "stuck_pull_requests"),
        ("Needs First Response", "response_debt"),
        ("Stale Queue", "stale_items"),
        ("Quick Wins", "quick_wins"),
    ):
        if key == "release_blockers":
            lines.extend(_markdown_release_blockers(report.queues[key], report.generated_at, limit=limit))
        else:
            lines.extend(_markdown_queue(title, report.queues[key], report.generated_at, limit=limit))

    lines.extend(_markdown_duplicate_candidates(report.duplicate_candidates, limit=limit))

    lines.extend(
        [
            "---",
            "",
            "Generated by Maintainer Pulse. Verify labels and context before making release decisions.",
            "",
        ]
    )
    return "\n".join(lines)


def render_json(report: PulseReport, *, limit: int = 25) -> str:
    return json.dumps(report_to_dict(report, limit=limit), indent=2, sort_keys=True)


def render_csv(report: PulseReport, *, limit: int = 25) -> str:
    output = io.StringIO()
    writer = csv.DictWriter(
        output,
        fieldnames=[
            "queue",
            "number",
            "title",
            "type",
            "state",
            "labels",
            "milestone",
            "author",
            "comments",
            "idle_days",
            "age_days",
            "created_at",
            "updated_at",
            "closed_at",
            "url",
        ],
    )
    writer.writeheader()
    for queue_name, items in report.queues.items():
        for item in items[:limit]:
            writer.writerow(_csv_item(queue_name, item, report.generated_at))
    return output.getvalue()


def render_html(report: PulseReport, *, limit: int = 10) -> str:
    data = report_to_dict(report, limit=limit)
    metrics = data["metrics"]
    queue_sections = []
    for title, key in (
        ("Release Blockers", "release_blockers"),
        ("Stuck Pull Requests", "stuck_pull_requests"),
        ("Needs First Response", "response_debt"),
        ("Stale Queue", "stale_items"),
        ("Quick Wins", "quick_wins"),
    ):
        rows = "".join(_html_item(item) for item in data["queues"][key])
        if not rows:
            rows = "<p class=\"empty\">No items in this queue.</p>"
        queue_sections.append(f"<section><h2>{html.escape(title)}</h2>{rows}</section>")

    recommendations = "".join(
        f"<li>{html.escape(recommendation)}</li>" for recommendation in data["recommendations"]
    )
    ai_summary = ""
    if data["ai_summary"]:
        ai_summary = f"""<section class="recommendations">
      <h2>AI Maintainer Summary</h2>
      <p class="meta">Provider: {html.escape(data["ai_summary"]["provider"])} - Model: {html.escape(data["ai_summary"]["model"])}</p>
      <p class="meta">AI-generated guidance is advisory. Verify repository context before acting.</p>
      <div>{_html_markdownish(data["ai_summary"]["text"])}</div>
    </section>"""
    duplicates = "".join(_html_duplicate(candidate) for candidate in data["duplicate_candidates"])
    if not duplicates:
        duplicates = "<p class=\"empty\">No likely duplicate candidates found.</p>"
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Maintainer Pulse: {html.escape(report.repository)}</title>
  <style>
    :root {{
      color-scheme: light dark;
      --accent: #0b7a75;
      --ink: #172026;
      --muted: #5c6670;
      --line: #d9e0e5;
      --surface: #f7faf9;
    }}
    body {{
      margin: 0;
      font: 16px/1.5 ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: var(--ink);
      background: #fff;
    }}
    main {{ max-width: 1080px; margin: 0 auto; padding: 40px 20px 64px; }}
    h1 {{ font-size: clamp(2rem, 4vw, 3.25rem); line-height: 1.05; margin: 0 0 8px; }}
    h2 {{ font-size: 1.25rem; margin: 32px 0 12px; }}
    .meta {{ color: var(--muted); margin: 0 0 28px; }}
    .metrics {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 12px;
      margin: 24px 0;
    }}
    .metric {{ border: 1px solid var(--line); border-radius: 8px; padding: 14px; background: var(--surface); }}
    .metric strong {{ display: block; font-size: 1.8rem; line-height: 1.1; }}
    .metric span {{ color: var(--muted); font-size: .9rem; }}
    .recommendations {{ border-left: 4px solid var(--accent); padding-left: 18px; }}
    .item {{ border-top: 1px solid var(--line); padding: 14px 0; }}
    .item a {{ color: var(--accent); font-weight: 700; text-decoration: none; }}
    .item p {{ margin: 4px 0 0; color: var(--muted); }}
    .labels {{ margin-top: 8px; display: flex; gap: 6px; flex-wrap: wrap; }}
    .label {{ font-size: .78rem; border: 1px solid var(--line); border-radius: 999px; padding: 2px 8px; }}
    .empty {{ color: var(--muted); }}
    @media (prefers-color-scheme: dark) {{
      body {{ background: #111719; color: #edf5f4; }}
      :root {{ --ink: #edf5f4; --muted: #9fb0b6; --line: #2b383c; --surface: #162124; }}
    }}
  </style>
</head>
<body>
  <main>
    <h1>Maintainer Pulse: {html.escape(report.repository)}</h1>
    <p class="meta">Generated {html.escape(data["generated_at"])}</p>
    <div class="metrics">
      <div class="metric"><strong>{metrics["health_score"]}/100</strong><span>Health score</span></div>
      <div class="metric"><strong>{metrics["open_issues"]}</strong><span>Open issues</span></div>
      <div class="metric"><strong>{metrics["open_pull_requests"]}</strong><span>Open PRs</span></div>
      <div class="metric"><strong>{metrics["release_blockers"]}</strong><span>Release blockers</span></div>
      <div class="metric"><strong>{metrics["stuck_pull_requests"]}</strong><span>Stuck PRs</span></div>
      <div class="metric"><strong>{metrics["response_debt"]}</strong><span>Needs first response</span></div>
    </div>
    <section class="recommendations">
      <h2>Recommended Maintainer Block</h2>
      <ul>{recommendations}</ul>
    </section>
    {ai_summary}
    {''.join(queue_sections)}
    <section><h2>Duplicate Candidates</h2>{duplicates}</section>
  </main>
</body>
</html>
"""


def _markdown_queue(
    title: str,
    items: list[WorkItem],
    now: datetime,
    *,
    limit: int,
) -> list[str]:
    lines = [f"## {title}", ""]
    if not items:
        lines.extend(["No items in this queue.", ""])
        return lines

    lines.extend(_markdown_items_table(items[:limit], now))
    lines.append("")
    return lines


def _markdown_release_blockers(
    items: list[WorkItem],
    now: datetime,
    *,
    limit: int,
) -> list[str]:
    lines = ["## Release Blockers", ""]
    if not items:
        lines.extend(["No items in this queue.", ""])
        return lines

    grouped: dict[str, list[WorkItem]] = {}
    for item in items[:limit]:
        grouped.setdefault(item.milestone_title or "No milestone", []).append(item)

    for milestone in sorted(grouped, key=lambda name: (name == "No milestone", name.lower())):
        lines.extend([f"### {escape_markdown(milestone)}", ""])
        lines.extend(_markdown_items_table(grouped[milestone], now))
        lines.append("")
    return lines


def _markdown_items_table(items: list[WorkItem], now: datetime) -> list[str]:
    lines = ["| Item | Labels | Idle | Age |", "| --- | --- | ---: | ---: |"]
    for item in items:
        item_link = f"[#{item.number} {escape_markdown(item.title)}]({item.html_url})"
        labels = ", ".join(item.labels) if item.labels else "-"
        lines.append(
            f"| {item_link} | {escape_markdown(labels)} | {idle_days(item, now)}d | "
            f"{age_days(item, now)}d |"
        )
    return lines


def _markdown_duplicate_candidates(
    candidates: list[DuplicateCandidate],
    *,
    limit: int,
) -> list[str]:
    lines = ["## Duplicate Candidates", ""]
    if not candidates:
        lines.extend(["No likely duplicate candidates found.", ""])
        return lines

    lines.extend(
        [
            "| Items | Similarity | Shared terms |",
            "| --- | ---: | --- |",
        ]
    )
    for candidate in candidates[:limit]:
        first = candidate.first
        second = candidate.second
        first_link = f"[#{first.number} {escape_markdown(first.title)}]({first.html_url})"
        second_link = f"[#{second.number} {escape_markdown(second.title)}]({second.html_url})"
        shared = ", ".join(candidate.shared_terms)
        lines.append(
            f"| {first_link}<br>{second_link} | {candidate.similarity:.2f} | "
            f"{escape_markdown(shared)} |"
        )
    lines.append("")
    return lines


def report_to_dict(report: PulseReport, *, limit: int) -> dict[str, Any]:
    return {
        "repository": report.repository,
        "generated_at": report.generated_at.isoformat(timespec="seconds"),
        "stale_days": report.stale_days,
        "metrics": report.metrics.__dict__,
        "ai_summary": (
            {
                "provider": report.ai_provider or "",
                "model": report.ai_model or "",
                "text": report.ai_summary,
            }
            if report.ai_summary
            else None
        ),
        "duplicate_candidates": [
            _duplicate_candidate_to_dict(candidate) for candidate in report.duplicate_candidates[:limit]
        ],
        "recommendations": report.recommendations,
        "queues": {
            name: [_item_to_dict(item, report.generated_at) for item in items[:limit]]
            for name, items in report.queues.items()
        },
    }


def _duplicate_candidate_to_dict(candidate: DuplicateCandidate) -> dict[str, Any]:
    return {
        "first": _item_summary(candidate.first),
        "second": _item_summary(candidate.second),
        "similarity": candidate.similarity,
        "shared_terms": list(candidate.shared_terms),
    }


def _item_summary(item: WorkItem) -> dict[str, Any]:
    return {
        "number": item.number,
        "title": item.title,
        "html_url": item.html_url,
        "labels": list(item.labels),
    }


def _item_to_dict(item: WorkItem, now: datetime) -> dict[str, Any]:
    return {
        "number": item.number,
        "title": item.title,
        "state": item.state,
        "labels": list(item.labels),
        "author": item.author,
        "html_url": item.html_url,
        "milestone_title": item.milestone_title,
        "created_at": item.created_at.isoformat(timespec="seconds"),
        "updated_at": item.updated_at.isoformat(timespec="seconds"),
        "closed_at": item.closed_at.isoformat(timespec="seconds") if item.closed_at else None,
        "comments": item.comments,
        "is_pull_request": item.is_pull_request,
        "idle_days": idle_days(item, now),
        "age_days": age_days(item, now),
    }


def _csv_item(queue_name: str, item: WorkItem, now: datetime) -> dict[str, Any]:
    return {
        "queue": queue_name,
        "number": item.number,
        "title": item.title,
        "type": "pull_request" if item.is_pull_request else "issue",
        "state": item.state,
        "labels": "; ".join(item.labels),
        "milestone": item.milestone_title or "",
        "author": item.author,
        "comments": item.comments,
        "idle_days": idle_days(item, now),
        "age_days": age_days(item, now),
        "created_at": item.created_at.isoformat(timespec="seconds"),
        "updated_at": item.updated_at.isoformat(timespec="seconds"),
        "closed_at": item.closed_at.isoformat(timespec="seconds") if item.closed_at else "",
        "url": item.html_url,
    }


def _html_item(item: dict[str, Any]) -> str:
    labels = "".join(f"<span class=\"label\">{html.escape(label)}</span>" for label in item["labels"])
    url = html.escape(item["html_url"])
    title = html.escape(item["title"])
    details = [
        f"{item['idle_days']} idle days",
        f"{item['age_days']} days old",
        f"{item['comments']} comments",
    ]
    if item["milestone_title"]:
        details.append(f"milestone: {html.escape(item['milestone_title'])}")
    return f"""<article class="item">
  <a href="{url}">#{item["number"]} {title}</a>
  <p>{' · '.join(details)}</p>
  <div class="labels">{labels}</div>
</article>"""


def _html_duplicate(candidate: dict[str, Any]) -> str:
    first = candidate["first"]
    second = candidate["second"]
    shared = ", ".join(candidate["shared_terms"]) or "-"
    return f"""<article class="item">
  <a href="{html.escape(first["html_url"])}">#{first["number"]} {html.escape(first["title"])}</a>
  <p>Likely duplicate of <a href="{html.escape(second["html_url"])}">#{second["number"]} {html.escape(second["title"])}</a></p>
  <p>Similarity: {candidate["similarity"]:.2f} - Shared terms: {html.escape(shared)}</p>
</article>"""


def _html_markdownish(value: str) -> str:
    paragraphs = [paragraph.strip() for paragraph in value.split("\n\n") if paragraph.strip()]
    return "".join(f"<p>{html.escape(paragraph)}</p>" for paragraph in paragraphs)


def escape_markdown(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _display_optional(value: float | None) -> str:
    return "-" if value is None else str(value)
